version: '2.4'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - "./docker/mongo_data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongoadmin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
